### ISSUE TITLE
PHP 5.6 only

### ISSUE THREAD

**Issue by gpilla** [ldaptools/ldaptools#1]
Hi,

I want to ask if there is a technology problem to work in 5.5 ... it still common to be much servers on 5.5 o 5.4... 

If there is a hard problem with 5.5 ... and only works on 5.6... forget my issue... i was "just asking"

**Comment by ChadSikorra** [comment]
There is no specific technical reason why the code couldn't be written to work with PHP 5.5 or lower. However, I have been using PHP 5.6 features in the code so changing it at this point would be problematic. 

I opted to make PHP 5.6 the required version for several reasons:
* It was the most current stable version of PHP available when I started writing the library.
* PHP 5.6 will be the last version in the 5.X line to be released. So I can take advantage of any 5.X features within the code.
* The 'splat' operator introduced in 5.6 has been extremely helpful and I've used it in a lot of places, especially when you can use it to type hint as well. Sprinkling `func_get_args()` everywhere was just annoying. 
* The `ldap_escape()` and `ldap_modify_batch()` functions were introduced in 5.6 and have been very useful (seems that `ldap_modify_batch()` was back-ported to 5.4 and 5.5 at later versions). Sure, I could've done without them but it's nice not to have to write your own stuff to fill that gap.
* Being able to define an array constant is very handy.

PHP 5.4 will actually be end of support in 2 months, with no further security updates. PHP 5.5 goes end of active support in 2 months, but will receive security updates for another year. So 5.6 will at least have a bit on longevity left.

Hopefully this will be less of an issue once people start to upgrade to the latest distros, of which pretty much all ship PHP 5.6 standard. But of course then there's the Ubuntu LTS version and unfortunately the next server version of that to come with 5.6 doesn't release until next year I think.

**Comment by gpilla** [comment]
Fitst at all thanks for your fast reply.

I agree your points, just asking incase was a composer misconfiguration... or an arbitrary decision.

Thanks.
