### ISSUE TITLE
ldap_connect support multiple urls

### ISSUE THREAD

**Issue by douyu** [ldaptools/ldaptools#11]
I read the comment here: http://php.net/manual/zh/function.ldap-connect.php
ldap_connect support multiple urls separated by space, so i supposed, there is no need to use LdapServerPool get available server, just pass then all, the ldap-ext will choose a server that worked.

**Comment by ChadSikorra** [comment]
The main reason I implemented that was so that I could both easily determine what server name the connection ends up on and easily control the initial connection timeout settings. If both of those can be accomplished without the need for that class then I wouldn't be opposed to just passing a list of URIs separated by spaces.

It seems like it is possible to get the current LDAP server with `ldap_get_option($ds, LDAP_OPT_HOST_NAME, $hostname);`. But based on some digging around it appears that the `LDAP_OPT_TIMEOUT` option has been broke in multiple versions of the OpenLDAP library. Perhaps it is fixed in newer releases?

**Comment by douyu** [comment]
I'm not clear about timeout broken, but i find something from php official documents， ldap_connect($host)`  does not open a connection. It checks whether the given parameters are plausibe and can be used to open a connection as soon as one is needed, `ldap_bind($ds,$user,$pwd)` timeout can set by `ldap_set_option($ds, LDAP_OPT_NETWORK_TIMEOUT, $timeout);`

**Comment by ChadSikorra** [comment]
Yeah, I see conflicting examples of this in different bug reports, such as: https://bugs.php.net/bug.php?id=69574. I'll have to test different versions to simulate a timeout. If I can get it working reliably then I'll just use that method.

The docs also say that you can't specify a port in the URI string, which is not correct based on my testing. Some of the LDAP docs really need some updating.

**Comment by douyu** [comment]
ldap-ext source code:  https://github.com/php/php-src/blob/master/ext/ldap/ldap.c
```c
		int rc = LDAP_SUCCESS;
		char	*url = host;
		if (!ldap_is_ldap_url(url)) {
			int	urllen = hostlen + sizeof( "ldap://:65535" );

			if (port <= 0 || port > 65535) {
				php_error_docref(NULL, E_WARNING, "invalid port number: " ZEND_LONG_FMT, port);
				RETURN_FALSE;
			}

			url = emalloc(urllen);
			snprintf( url, urllen, "ldap://%s:" ZEND_LONG_FMT, host ? host : "", port );
		}

#ifdef LDAP_API_FEATURE_X_OPENLDAP
		/* ldap_init() is deprecated, use ldap_initialize() instead.
		 */
		rc = ldap_initialize(&ldap, url);
#else /* ! LDAP_API_FEATURE_X_OPENLDAP */
		/* ldap_init does not support URLs.
		 * We must try the original host and port information.
		 */
		ldap = ldap_init(host, port);
		if (ldap == NULL) {
			efree(ld);
			php_error_docref(NULL, E_WARNING, "Could not create session handle");
			RETURN_FALSE;
		}
#endif /* ! LDAP_API_FEATURE_X_OPENLDAP */
```
only define LDAP_API_FEATURE_X_OPENLDAP can use ldap urls

**Comment by ChadSikorra** [comment]
So basically that means the use of a URI was a OpenLDAP library specific option. I think they should just remove that statement from the docs.

But anyway, I did get around to some testing of `LDAP_OPT_NETWORK_TIMEOUT`. This option seems to behave...oddly. Setting it to 1 seems to cause a timeout in 2 seconds or so, setting it to 5 causes a timeout in 10 seconds...etc. I think something is ultimately botched in the LDAP extension with how it handles setting the timeout. I wonder if perhaps the order of the if/elif constant checks are reversed for the logic, or something else is going on. See here: https://github.com/php/php-src/blob/master/ext/ldap/ldap.c#L2350 . I can futz with the extension a bit and recompile to see if iI can get it to behave as expected. But until I get some reliable timeout setting it seems like the server pool class is the best method to take at the moment. Unless you see different results?

**Comment by douyu** [comment]
I test with `LDAP_OPT_TIMEOUT` and `LDAP_OPT_NETWORK_TIMEOUT`, `LDAP_OTP_TIMEOUT` works fine,   but what value set for `LDAP_OPT_NETWORK_TIMEOUT` cause timeout after 20sec.  Maybe ldap-ext has bug for timeout setting or the timeout setting depends on other condition which we don't known at prement. Just keep the server pool implement for now.

**Comment by ChadSikorra** [comment]
Even with `LDAP_OPT_TIMEOUT` and `LDAP_OPT_NETWORK_TIMEOUT` I don't get accurate timeout values for an unavailable server, on Ubunutu anyways with OpenLDAP 2.4.42. Closing this unless we can somehow get it to provide an accurate timeout setting.

On a separate note, it would be nice if I had a "retry" mechanism for the connection somewhere. I could potentially catch a LdapConnectionException and do an auto-retry of the connection; probably somewhere in the operation invoker class would make sense. This could potentially help if while executing operations the active LDAP server goes down.
