### ISSUE TITLE
Automatic reset attributes when modifying ldap objects

### ISSUE THREAD

**Issue by NyroTheCat** [ldaptools/ldaptools#12]
Hi chad,

i have another request for you: the setter methods of ldap objects are not aware about empty values. if you set an attribute with an empty value (`''`, `NULL`, `[]`) then the persist process will fail. you have to explicity call the `reset()` method on attributes to clear (delete) them.

```php
$user->setTitle('');
$user->set('title', '');
$user->title = '';
```

would it be possible to check the value inside the setters? so if the value is empty, reset an clear the attribute automatically?

**Comment by ChadSikorra** [comment]
This sort of feature has crossed my mind too as I've been making changes in the different attribute converters. I'll have to think about it though, as I'm not sure how/if I want to do this.

**Comment by NyroTheCat** [comment]
i thought about something like this #13

**Comment by ChadSikorra** [comment]
Closing, merged PR https://github.com/ldaptools/ldaptools/pull/13. Thanks!
