### ISSUE TITLE
ConfigurationParseTrait use_paging ignored

### ISSUE THREAD

**Issue by jelleheemskerk** [ldaptools/ldaptools#14]
In [ConfigurationParseTrait.php](https://github.com/ldaptools/ldaptools/blob/bcb0f9667c3f9802765e893cc922a68c4689a23e/src/LdapTools/ConfigurationParseTrait.php#L57) on line **57**

`return array_filter($existingConfig);`

Removes `use_paging` when the value is _false_.

**Comment by ChadSikorra** [comment]
Fixed in https://github.com/ldaptools/ldaptools/commit/852299e30d267aa3f2d507ade924eba4c1fdbb30. Thanks for reporting this!
