### ISSUE TITLE
LDAP Add Operation Error: Object class violation with OpenLDAP

### ISSUE THREAD

**Issue by zneel** [ldaptools/ldaptools#15]
Hi folks,
I'm trying to create a user with your lib, and I can't find why It is not working,
I'm connected to my openldap server and when I'm using the method `createUser()` I just get a LDAP Add Operation Error: Object class violation.
Any idea?
My schema is like this:
        type: user
        # The LDAP objectClass
        class: ['top', 'person', 'organizationalPerson', 'inetOrgPerson']

**Comment by ChadSikorra** [comment]
More than likely you're missing a required attribute. I have not done much with the OpenLDAP schema, but I did use it while I was testing and created lots of users with it. Hopefully I can check this out later tonight.

**Comment by zneel** [comment]
@ChadSikorra Do you have any idea about which attribute is required to create a LDAP user? 
I used cn and sn, I think on my schema it's name and lastName.
Thanks for your answer, I saw you made a Bundle for symfony, I'm currently using symfony with sonatauser and trying to map user management with sonata to ldap.

**Comment by ChadSikorra** [comment]
I think the `UID` attribute is required as well. But off hand I'm not positive on that, as it could be generated automatically on creation.

**Comment by zneel** [comment]
`            $ldapObject = $ldap->createLdapObject();
            $ldapObject->createUser()
                ->in('ou=SI,cn=ldaprt,dc=ip-176-31-232,dc=eu')
                ->with([
                    'name' => 'john',
                    'lastName' => 'cena',
                ])
                ->execute();
`
here is my query, and my schema looks like this:
`        
class: ['top', 'person', 'organizationalPerson', 'inetOrgPerson']
`
I tried a few thinks but still can't get it to work properly
any idea of what I'm doing wrong?

**Comment by zneel** [comment]
I fixed my issue, I have a suggestion concerning the library, maybe you should add `getDiagnosticMessage()` by default for debugging purposes I had to dump into the vendor to have a proper error message !
Anyway, thanks. I was missing in my user schema
``` yaml
        default_values:
            objectclass: [ 'top', 'inetOrgPerson' ]
```

**Comment by ChadSikorra** [comment]
Glad to hear you solved it! The last day or two has been...interesting, to say the least. So I haven't had much time at the moment. I think you're right, I should just use the diagnostic message by default as it provides much better details. I'll leave this open until that's changed. Thanks for the suggestion and reporting this.

**Comment by ChadSikorra** [comment]
I added the diagnostic message with this commit: https://github.com/ldaptools/ldaptools/commit/9b65ba3ea358edba4635927b62c3fd3149aeefc0. I will hopefully tag a new version within a month or so. I'm currently working on finishing ACL/ACE parsing of AD security descriptors and Exchange Mailbox creation.
