### ISSUE TITLE
Attempted to call an undefined method named "isRecursivelyMemberOf"

### ISSUE THREAD

**Issue by thlbaut** [ldaptools/ldaptools#16]
I'm trying to use filter with the following request 

```
use LdapTools\Configuration;
use LdapTools\LdapManager;
use LdapTools\Object\LdapObjectType;

[...]

$query = $ldap->buildLdapQuery();

// The $group can be a typical AD group name, DN, GUID, or SID.
$users = $query->fromUsers()
    ->where($query->filter()->isRecursivelyMemberOf($dn))
    ->getLdapQuery()
    ->getResult();

[...]
```

but I get this error : 

> [2016-11-28 11:23:27] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "isRecursivelyMemberOf" of class "LdapTools\Query\Builder\FilterBuilder"." at [...] line 26 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"isRecursivelyMemberOf\" of class \"LdapTools\\Query\\Builder\\FilterBuilder\". at [...]:26)"} []

Thanks for your help !

**Comment by ChadSikorra** [comment]
Hello! I'm guessing you're using OpenLDAP? I don't have a recursive group strategy/method in place for OpenLDAP at the moment. It doesn't support the extensible match filter `LDAP_MATCHING_RULE_IN_CHAIN`, which is what AD uses. I think the best way to handle it in OpenLDAP would probably be a new attribute assigned to an attribute converter that walks the results of the group membership.

**Comment by thlbaut** [comment]
Hello ! 

Yes, you're right ! Thank you for your quick reply, so I'll consider an alternative solution :)

Thank you!
