### ISSUE TITLE
filter dn parts

### ISSUE THREAD

**Issue by markusu49** [ldaptools/ldaptools#18]
OpenLDAP allows search filters matching parts of the dn like this: 

`(ou:dn:=people)`

Creating such a filter with ldaptools like this:

```
objects:
  person:
    filter:
      eq: ['ou:dn:', 'people']
```

results in an exception:

> Attribute "ou:dn:" is not a valid name or OID.

**Comment by ChadSikorra** [comment]
Updating the regex might be the quickest workaround, but I think what I need to do is fix the [MatchingRule](https://github.com/ldaptools/ldaptools/blob/master/src/LdapTools/Query/Operator/MatchingRule.php) operator to work for all extensible matching rule types. Then I need to add a few more filter shortcuts, such as: `matchPart($attribute, $part, $value)` for the matching rule you're describing.

The allowed extensible matching syntax appears to be:

      extensible     = ( attr [dnattrs]
                           [matchingrule] COLON EQUALS assertionvalue )
                       / ( [dnattrs]
                            matchingrule COLON EQUALS assertionvalue )

According to the [RFC](https://tools.ietf.org/search/rfc4515) anyway. So actually my current matching rule would work for this example, but it's not intuitive and has not filter shortcut method:

```php
use LdapTools\Query\Operator\MatchingRule;

$results = $ldap->buildLdapQuery()
    ->where(new MatchingRule('ou','dn','people'))
    ->getLdapQuery()
    ->getResult();
```

You could even add this to an event so it's set for the type every time:

```php
use LdapTools\Event\Event;
use LdapTools\Event\LdapObjectSchemaEvent;
use LdapTools\Object\LdapObjectType;
use LdapTools\Query\Operator\bAnd;
use LdapTools\Query\Operator\MatchingRule;

$ldap->getEventDispatcher()->addListener(Event::LDAP_SCHEMA_LOAD, function(LdapObjectSchemaEvent $event) {
    $schema = $event->getLdapObjectSchema();

    // Or whatever you called the type...
    if ($schema->getObjectType() == 'person') {
        $schema->setFilter(new bAnd(new MatchingRule('ou','dn','people')));
    }
});
```

**Comment by ChadSikorra** [comment]
Fixed with https://github.com/ldaptools/ldaptools/commit/060312f5e7eb5cf797368957263d2c8927855bb3. In the schema filter you can now do:

```yaml
objects:
  person:
    type: person
    filter:
      match_dn: ['ou', 'people']
```

You can can also create any generic matching rule using the `match()` method of the filter builder. Added some docs [here](https://github.com/ldaptools/ldaptools/blob/master/docs/en/tutorials/Building-LDAP-Queries.md#matchattribute-rule-value-dnflag--false).

```php
$query = $ldap->buildLdapQuery();

$result = $query->where($query->filter()->matchDn('ou', 'Sales'))
    ->andWhere($query->filter()->match('givenName', 'caseExactMatch', 'John'))
    ->getLdapQuery()
    ->getResult();
```
