### ISSUE TITLE
make schema available for event listeners

### ISSUE THREAD

**Issue by markusu49** [ldaptools/ldaptools#20]
It might be helpful to have the schema available on creation events. Current use case:

When creating an object of a certain type, I need to automatically generate a set of children under it. Inside the afterCreationEvent, I cannot say for sure what kind of object was created and therefore do not know if I have to generate the children or not.

**Comment by ChadSikorra** [comment]
Fixed with https://github.com/ldaptools/ldaptools/commit/be1957fcd86dd7d1df0e2104c7f31b341429db32. I didn't want to add the schema object itself to the event though, I just added the schema type name.  So you can now do:

```php
if ($event->getType() === 'user') {
}
```

**Comment by markusu49** [comment]
Why not add the whole schema object? Another idea was to set the ldap objectClass based on the schema class attribute in the beforeCreation event handler.

I'll try this now by setting the default_values attribute in the schema load event handler, where the schema object is available.

**Comment by ChadSikorra** [comment]
I don't want people to be too reliant on the LdapObjectSchema itself. You can use the schema factory from the LdapManager class to retrieve the schema though:

 `$schemaObject = $ldap->getSchemaFactory()->get($schemaName, $type);`

However, that may change eventually. I was thinking of having a simple LdapSchema collection class that contains all the LdapObjectSchema objects that could be passed around. So the schema factory may change at some point.
