### ISSUE TITLE
Modify dn attribute of existing entry

### ISSUE THREAD

**Issue by markusu49** [ldaptools/ldaptools#23]
Have you implemented the `moddn` changetype somewhere? Couldn't find anything about it in the docs. Just setting the cn attribute (or whatever it is called) on an LdapObject and persisting it doesn't seem to work:

> LDAP Batch Modify Operation Error. Diagnostic message: "value of naming attribute 'cn' is not present in entry"

**Comment by ChadSikorra** [comment]
Are you trying to move the LDAP object to a different location, or just
rename it?

**Comment by markusu49** [comment]
I'm trying to rename it. Just found this code working:

```
$operation = new RenameOperation(
    'cn=oldname,ou=people,o=myorg',
    'cn=newname',
    'ou=people,o=myorg',
    true
);
$ldap->getConnection()->execute($operation);
```

Do you think it would make sense to implement it the set-attribute-and-persist way?

**Comment by ChadSikorra** [comment]
Yeah, that's currently the only way to do it at the moment. I recently added the `rdn` option to the schema, so this should be detectable on a persist now. I just need to add the logic into the LdapObjectManager. And it should probably have a rename event.

**Comment by ChadSikorra** [comment]
You can now do a rename in the set-attribute-and-persist way like you mentioned: https://github.com/ldaptools/ldaptools/commit/51acb2d1e9cbf87591d0c0aed7f9b24d49b65459.

I need to revisit this at some point, as it doesn't handle multivalued RDNs and it should probably be an attribute converter that implements an operation generator. But existing limitations forced me to do it this way. Anywho, closing this. Apologies it took so long to implement. Hopefully I'll get around to tagging a new version soon.
