### ISSUE TITLE
"deprecated" messages

### ISSUE THREAD

**Issue by webbird** [ldaptools/ldaptools#25]
Hi, I am just playing around a little bit with this great tools and am getting some "deprecated" messages:

PHP Deprecated:  Not quoting the scalar "%username%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0. in PATH\vendor\symfony\yaml\Inline.php on line 325

Please note: I am using XDebug with SCREAM option and PHP error reporting turned on. I know these messages are not visible in production environments. I am just reporting this in case you missed it.

**Comment by ChadSikorra** [comment]
Hmmm...I think that's being triggered by this:

https://github.com/ldaptools/ldaptools/blob/master/resources/schema/ad.yml#L218

I'll update that later today. Thanks for heads-up on that.

**Comment by ChadSikorra** [comment]
Should be fixed with https://github.com/ldaptools/ldaptools/commit/12599b298e2274dfd19e44b4a1343cfc0a1f5d56. Let me know if you still notice the messages.
