### ISSUE TITLE
Q: How to add/use an LDAP filter

### ISSUE THREAD

**Issue by webbird** [ldaptools/ldaptools#26]
In my current project, there will be a configuration that allows users (=admins) to set an LDAP filter. It would be great if that could be combined with the query builder. Example: Base configuration is to find "users", the filter the admin configures is something like "(cn=b*)". The combined filter would be

(&(objectCategory=person)(objectClass=user)(cn=b*))

Can this be done?

(Note: I am not using YAML but JSON config files. It _may_ be an option to configure the filter in JSON like it would be done in YAML so I can pass it as an array.)

**Comment by ChadSikorra** [comment]
That would look something like:

```php
$name = 'b*';

$qb = $ldap->buildLdapQuery()->from('user');
# The 'like' shortcut method does not escape any wildcards...
$qb->where($qb->filter()->like('name', $name));

$users = $qb->getLdapQuery()->getResult();
```

But from what I understand you want a way to combine an existing LDAP filter string into an existing query builder object? Something like:

```php
$filter = '(cn=b*)';

$users = $ldap->buildLdapQuery()
    ->from('user')
    ->addRawFilter($filter)
    ->getLdapQuery()
    ->getResult();
```

Is that correct?

**Comment by webbird** [comment]
Thanks for answering this fast. Yes, that's what I meant.

This is what I have tried since opening the issue: Having a config like this...

    "find": "users",
    "filter": [
        { "present": "sn" },
        { "present": "givenname" }
    ],
    ...

...and some code like this (not the complete code...)...

                        $lqb->from(self::$map[$what]);
                        ...
                        foreach($item as $shortcut => $query)
                        {
                           $lqb->where(
                               ( count($query) > 1
                                 ? $lqb->filter()->$shortcut($query[0],$query[1])
                                 : $lqb->filter()->$shortcut($query[0])
                               )
                           );
                        }

...I am getting a somewhat strange LDAP filter:

    (&(&(objectCategory=person)(objectClass=user))(&(s=*)(g=*)))

Are there any limitations combining from() and filter shortcuts? Or did I just do something wrong?

Thanks in advance!

**Comment by ChadSikorra** [comment]
That query looks correct for what you're telling it (well, with some minor issues...). You're asking LDAP for all users that have a value present in `sn` or `givenName`. But somehow you're only getting the first letter of those two attribute names. That's because `$query` is the string attribute name and you're selecting the first character from it. I think you need `$lqb->filter()->$shortcut($query)`. I think you need to check if `$query` is an array then the array access to it for the first and second values would make sense.

There's also an undocumented class I have here:

https://github.com/ldaptools/ldaptools/blob/master/src/LdapTools/Utilities/ArrayToOperator.php

It takes a filter in array format and converts it to an operator you could add to the query builder. Such as:

```php
use LdapTools\Utilities\ArrayToOperator;

$filter = [
    ['present' => 'sn'],
    ['present' => 'givenName'],
    ['like' => ['cn', 'b*']],
];
$ob = new ArrayToOperator();
$where = $ob->toOperator($filter);

# Check the raw filter it produced...
var_dump($where->toLdapFilter());

$users = $ldap->buildLdapQuery()
    ->from('user')
    ->add($where)
    ->getLdapQuery()
    ->getResult();
```

**Comment by webbird** [comment]
The first letter issue is fixed, what I meant with 'strange' are the multiple *&*. ;) 

Generated:
    (&(&(objectCategory=person)(objectClass=user))(&(sn=*)(givenname=*)))

Should (could) be:
    (&(objectCategory=person)(objectClass=user)(sn=*)(givenname=*))

Anyway, the filter seems to work, no need to beautify it. ;) 

Thanks for posting the example, I will try that next week! I think that solution will be fine for me. I can now provide a nice GUI where the admin configures the clauses without having to know about LDAP filters. :)

I am happy that I've found this. Thanks for sharing your work!

**Comment by webbird** [comment]
Updated code example (it may help someone else...)

    foreach($item as $shortcut => $query)
    {
        if(is_array($query) && count($query) > 1)
        {
            $filter = $lqb->filter()->$shortcut($query[0],$query[1]);
        } else {
            $filter = $lqb->filter()->$shortcut($query);
        }
                            $lqb->where($filter);
                        }

**Comment by ChadSikorra** [comment]
Glad you figured something out! The strange multiple '&' you are seeing is mostly design related in LdapTools. Each schema type uses an initial AND filter to narrow results for that type. Then all of the other operators to further filter for a type are wrapped in another AND. And both of those are then wrapped into an overall AND to keep it altogether.

There probably could be some further optimization to "beautify" it like you say, but I guess I just haven't made it a priority yet. It will also break many specs when I do that unfortunately :/

**Comment by webbird** [comment]
No need to beautify as long as it works. ;)

**Comment by ChadSikorra** [comment]
Haha, ok (: Closing this issue for now then, as I would prefer to keep the raw LDAP filters out of the query builder for now, and the ArrayToOperator class can take care of pretty much any case. Allowing for raw LDAP filters opens up the potential for accidental things, like not escaping properly or malformed filters that mess the rest of it up.

**Comment by webbird** [comment]
Did not manage to try it out yet, but I will. Thank your for helping.
