### ISSUE TITLE
Cannot change AD passwords: DSID-031A11E5, problem 5003 (WILL_NOT_PERFORM)

### ISSUE THREAD

**Issue by skylarmt** [ldaptools/ldaptools#27]
I'm getting `
LDAP Batch Modify Operation Error. Diagnostic message: "0000001F: SvcErr: DSID-031A11E5, problem 5003 (WILL_NOT_PERFORM), data 0` when I try to run
```
$repository = $ldap->getRepository(LdapObjectType::USER);
$user = $repository->findOneByUsername($username);
$user->setPassword($password);
$ldap->persist($user);
```

I'm binding with an administrator account that can change user passwords on the server, the passwords work when setting them on the server (they don't fall foul of the password rules), and I'm using TLS for the connection.

I'm using a Windows Server 2008 VM for testing.

**Comment by ChadSikorra** [comment]
That seems very unusual. Are you able to create a LDAP user via this library? Such as:

```php
$ldap->createLdapObject(LdapObjectType::USER)
    ->with([
        'username' => 'foobar',
        'password' => $password,
    ])
    ->in('dc=mydomain,dc=local')
    ->execute();
```

That would have the same TLS requirements, so I would expect the same error message if that's somehow related. Also the requirement is that the connection be using at least 128bit SSL encryption. If not it will throw the diagnostic message above (Though it can throw that same diagnostic message for many different reasons). I kind of doubt that's the case here with a Server 2008 (I assume R2?) VM. Would it be possible to test from a different machine/VM? Also, what version of PHP are you using?

**Comment by skylarmt** [comment]
I did this:
```
$ldap->createLdapObject(LdapObjectType::USER)
        ->with([
            'username' => 'foobar2',
            'password' => "=n^&Q|bz5N",
            'dn' => "Foo Bar 2"
        ])
        ->in('cn=Users,dc=example,dc=com')
        ->execute();
```
and got no errors, and there is now a user `foobar2` on the server listed with the others.  I tried to change the user's password via my app, and it gives the same error as before.  Once again I can change the password from the server just fine.

The app itself is running on Ubuntu Linux (my Linux Mint development machine, to be precise).

```
skylar@skylar-Gazelle ~ $ php -v
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies
```

The Windows VM is Standard edition, Service Pack 1, 32 bit.  I had the install disk lying around, didn't feel like downloading an ISO on my terrible Internet connection (2Mbps when the weather is good), and it's on a host-only network without any actual Internet for updates.  AD has either a self-signed certificate or one from a CA I made with openssl.  I don't know which because SSL wouldn't work until I installed IIS and generated a new cert.  I also had to enable TLS 1.1 and 1.2 in the registry.

Changing AD passwords is the last core feature I have yet to implement in my app, so of course it's the one that gives all the trouble!

**Comment by ChadSikorra** [comment]
That narrows down the issue a little bit. The issue doesn't seem to be related to the TLS connection (on creation at least), or the attribute encoding process being used in the library to format the password properly to what is expected for the `unicodePwd` attribute.

The easiest way to get SSL/TLS working on a Windows VM is to install the Certificate Authority role on it (for purposes of self-contained testing anyway). Reboot the VM afterwards and TLS will be available. I've actually never explicitly created a CSR or generated a signed cert for LDAP using only IIS/OpenSSL.

If I had to guess I'd think the issue is probably related to the certificate being used by AD at the moment. Though why it works on creation and not on a modification I'm not sure. I think at this point you might have to enable advanced logging on AD to see if you can get a better error message:

https://support.microsoft.com/en-us/help/314980/how-to-configure-active-directory-and-lds-diagnostic-event-logging

Another possibility that might give you more information is to turn on PHP LDAP debugging to max. Just put this at the top of your PHP script: `ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);`. Run it from the console and you should see tons of information about what the PHP LDAP module is doing behind the scenes.

**Comment by skylarmt** [comment]
[PHP LDAP log](https://gist.github.com/skylarmt/ca1b69e21fb114305fd9160e63dd94a6)  
[Windows event log](https://gist.github.com/skylarmt/31e6872f56218afea71c1b9cc28a90c3)

```
Internal error: The operation on the object failed. 
 
Additional Data 
Error value:
2 0000208F: NameErr: DSID-031001D1, problem 2006 (BAD_NAME), data 8350, best match of:
	'sso@example.com'
```

LDAP configuration:
```
$ldap_config = new Configuration();
$ldap_config_domain = (new DomainConfiguration('example'))
        ->setDomainName("example.com")
        ->setServers(['192.168.25.131'])
        ->setUsername("sso")
        ->setPassword("P@ssword")
        ->setUseTls(TRUE);

$ldap_config->addDomain($ldap_config_domain);
```

**Comment by skylarmt** [comment]
To enable SSL in AD, I created a CSR, signed it, and installed it.  I also enabled TLS 1.2 in the registry.  Then I followed the instructions [here](http://www.torkwrench.com/2013/07/09/active-directory-over-ssl-banishing-8009030e-to-the-land-of-wind-and-ghosts/), then I enabled TLS 1.1 as well, and it started working after a reboot.

**Comment by ChadSikorra** [comment]
The internal error you quoted appears to be related to something else (the name matching for the initial bind I believe). None of the event log items strike me as relevant to the password change.  Unfortunately the PHP LDAP debug log doesn't give us anything helpful in this case.

I would check the security event log on the DC for something. Perhaps something is getting logged there? Guess I'm running out of things to check/test. A few list of things that you could try, some requiring way more effort than others:

* Try the same password change a very narrow Python script using LDAP with TLS (Something like [this](https://gist.github.com/artschwagerb/35130c93b276d6aa2b05)
* Remove the certificate you originally generated. Install the base Certificate Authority role on the DC (it will properly generate a certificate that I'm sure is valid for LDAP over TLS.
* Stand up a different DC based on Server 2012 or 2016, install a Certificate Authority role on it, then test the same thing (Yeah...the ISOs for these are huge, so might not be feasible for you :/ )

**Comment by skylarmt** [comment]
Well, I'm an idiot.  While debugging another issue, I found that the variable I was using to hold the new password was not only out of scope, but was also undefined.  Now that I fixed that, it works perfectly (except for AD's stupidly paranoid password complexity requirements, but that's a whole other problem).

At least this issue thread will likely be useful to someone in the future.

**Comment by wiryonolau** [comment]
This lib doesn't change password according to AD even if the engine is set to AD


To change password by the user we need to modify the operation to

```php
$old_password = "MY OLD PASSWORD";
$new_password = "MY NEW PASSWORD";

// Get the user, either use buildLdapQuery or repository
$user = $ldap->buildLdapQuery()->where(["name"=>$username])->getLdapQuery()->getSingleResult();

$encoder = new EncodeWindowsPassword();

// If Administrator
$user->set("unicodePwd", $encoder->toLdap($new_password));

// Force user must use old_password or when your bind using user
$user->setBatchCollection(
    new BatchCollection(
        $user->getDn(),
        new Batch(Batch::TYPE["REMOVE"], "unicodePwd", $encoder->toLdap($old_password)),
        new Batch(Batch::TYPE["ADD"], "unicodePwd", $encoder->toLdap($new_password))
    )
);

$ldap->persist($user);
```

If you got this
```
<acl_modify: attribute 'password' on entry 'CN=Test Gmail,OU=App Users,OU=App,DC=example,DC=com' was not found in the schema!>
```
Then make  sure to check the password policy, usually there is minimum age and history for reusing password
```
samba-tool domain passwordsettings show
samba-tool domain passwordsettings set --min-pwd-age=0 --history-length=1
```

Running with Samba AD 4.15 in docker, PHP 7.4
