### ISSUE TITLE
Problem with ConvertValueToDn class

### ISSUE THREAD

**Issue by masadelante** [ldaptools/ldaptools#4]
When trying to retrieve an object based on its RDN - in concreto, retrieving a group object in order to add it to a user - an exception is thrown because the attribute "distinguishedName" is not present in the object.

I solved the problem by modifying the buildLdapQuery function:

    protected function buildLdapQuery(array $filter, $isOrFilter)
    {
        $query = new LdapQueryBuilder($this->connection);
        $query->select('dn');

        $statement = $isOrFilter ? $query->filter()->bOr() : $query->filter()->bAnd();
        foreach ($filter as $attribute => $values) {
            $values = is_array($values) ? $values : [ $values ];
            foreach ($values as $value) {
                $statement->add($query->filter()->eq($attribute, $value));
            }
        }

        return $query->andWhere($statement);
    }
`

**Comment by ChadSikorra** [comment]
Thanks for reporting this! Is this in an OpenLDAP environment? I have a few ideas on how I can go about fixing this.

**Comment by masadelante** [comment]
Hello Chad,

That's correct, it's OpenLDAP. Note that the query runs all right, and returns the correct entry, it's just when the LdapObject checks if it has(attribute) that an exception is thrown.

Let me know if you need a few error logs.

Good luck - and many thanks for coding an impressive library!

**Comment by ChadSikorra** [comment]
Glad you find the library useful!

This should be fixed by https://github.com/ldaptools/ldaptools/commit/b21c6c267c3218e2b9df98741f067cf283f413c6, if I understand the problem correctly anyway. The `dn` value is always returned from a query regardless if it's selected or not, so it's probably best just to use that like you've shown. I tested in both AD and OpenLDAP and it works fine in both. Let me know if you still have issues with it.

**Comment by masadelante** [comment]
Hello Chad,

That fixed the problem as expected. Thank you for the prompt fix!

Best regards,

Denis

**Comment by ChadSikorra** [comment]
Thanks for the confirmation. I'll leave this open until I tag a new version, which will probably be in a couple weeks (currently working on a few different features to add).

**Comment by ChadSikorra** [comment]
Closing this, as it is fixed in v0.21.0.
