### ISSUE TITLE
Fatal error: Uncaught LdapTools\Exception\AttributeConverterException: Expected a string SID but got ....

### ISSUE THREAD

**Issue by robinfre** [ldaptools/ldaptools#40]
Hello,
I have a problem when I try to search LDAP for a SID.

My function and code looks like this.

```
    $search = "S-1-5-21-633360653--1776422187--939824731-1248";
    getUserBySID($search, $ldap);

function getUserBySID($search, $ldap_connection){
    $query = $ldap_connection->buildLdapQuery();
    $object = $query
            ->fromUsers()
            ->select(['name', 'description', 'sid'])
            ->Where(['SID' => $search])
            ->getLdapQuery()
            ->getOneOrNullResult();
}
```

I'll get this error:

> Fatal error: Uncaught LdapTools\Exception\AttributeConverterException: Expected a string SID but got "S-1-5-21-633360653--1776422187--939824731-1248".

How can I solve this issue?

Best regards
Robin

**Comment by ChadSikorra** [comment]
I think you have one too many dashes in the SID. It should be: `$search = "S-1-5-21-633360653--1776422187-939824731-1248"`.

**Comment by robinfre** [comment]
Now it works without an error but it can't find a result. I got the SID from the users object "SID" attribute.

My aim of the usage of the SID is to get it from a SQL database after it was written after a process. Maybe this helps to understand the problem.

**Comment by ChadSikorra** [comment]
Interesting. What does the Active Directory Users and Computers (ADUC) tool say that the SID actually is for the user? If you navigate straight to it you should be able to check the attribute editor tab then navigate to the value for "objectSid". Maybe I have a flaw in the decoding process. If you can get me the raw hex value for the objectSid attribute I should be able to figure it out.

ie:

```php
    $sid = $ldap_connection
            ->buildLdapQuery()
            ->fromUsers()
            ->select(['objectSid'])
            ->where(['username' => 'user'])
            ->getLdapQuery()
            ->getSingleScalarResult();

var_dump(bin2hex($sid));
```

**Comment by robinfre** [comment]
string(56) "0105000000000005150000000d51c025d5f21d96a569fbc7e0040000" 


![2017-11-02 20_53_19-dc2016 - remotedesktopverbindung](https://user-images.githubusercontent.com/5369995/32349713-4887eccc-c018-11e7-9c13-ecd707b1f488.png)

**Comment by ChadSikorra** [comment]
Well, it doesn't seem to be a conversion issue:

```php
 $sid = new \LdapTools\Security\SID(hex2bin('0105000000000005150000000d51c025d5f21d96a569fbc7e0040000'));

echo $sid->toString().PHP_EOL;
```

That outputs the expected string SID from the screenshot above. Did you use this same library to save the SIDs to the database initially? Also, are you on the latest version of the library?

**Comment by robinfre** [comment]
Yes I have one environment for the UI and the saving into the database.
```

 $sid = new \LdapTools\Security\SID(hex2bin('0105000000000005150000000d51c025d5f21d96a569fbc7e0040000'));

echo $sid->toString().PHP_EOL;
```

Output:

`S-1-5-21-633360653--1776422187--939824731-1248`

**Comment by ChadSikorra** [comment]
What's your PHP version, OS, and arch (32/64 bit)?

**Comment by robinfre** [comment]
I have updated the repository but theres nothing new.

I'm working in XAMPP for windows.

```

PHP Version 7.0.13
System 	Windows NT NBLEL 10.0 build 15063 (Windows 10) i586
Build Date 	Nov 8 2016 13:30:03
Compiler 	MSVC14 (Visual C++ 2015)
Architecture 	x86 
```

**Comment by ChadSikorra** [comment]
It seems to be an issue with 32bit PHP builds. It runs fine with PHP 7.0 x64. I was worried about that. The quickest way around that would be to use a 64bit build of PHP 7, which would circumvent the problem. The problem appears to be the pack functions inability to decode an unsigned 32 bit integer, little endian, on a 32bit platform.

Technically a PHP issue with that arch build, but I guess I need to find a proper workaround.

**Comment by robinfre** [comment]
Thanks for the information. I'll try a 64 bit build.

**Comment by ChadSikorra** [comment]
Workaround committed here https://github.com/ldaptools/ldaptools/commit/156c40f3173a318e4ac80e3068c3885c960bd31b. I will keep this open as I will likely tag a minor release addressing this, as my frequency of work on this library lately has gone down a bit. Thanks for reporting this!

**Comment by ChadSikorra** [comment]
Tagged a minor release, closing. Let me know if you still run into issues.
