### ISSUE TITLE
ldap_bind throw ErrorException

### ISSUE THREAD

**Issue by douyu** [ldaptools/ldaptools#9]
`PHP Fatal error:  Uncaught exception 'ErrorException' with message 'ldap_bind(): Unable to bind to server: Invalid credentials' in /mnt/hgfs/projects/hodor-otp/vendor/ldaptools/ldaptools/src/LdapTools/Connection/LdapConnection.php:285`

LdapConnection.php:285
`            $this->isBound = @ldap_bind(
                $this->connection,
                LdapUtilities::encode($username, $this->config->getEncoding()),
                LdapUtilities::encode($password, $this->config->getEncoding())
            );
`
the ldap_bind add the '@', but still throw exception, it seems not working

**Comment by ChadSikorra** [comment]
What version of PHP are you using? I don't think I've ever seen that behavior.

**Comment by douyu** [comment]
i test with php 5.6.23, ubuntu 14.04, it's very confused for me, why not working, i will keep find the reason

**Comment by ChadSikorra** [comment]
Ok, I think I understand what might be happening here. You most likely have a custom error handler set with `set_error_handler()` that throws ` \ErrorException`. I probably should account for that possibility and wrap a try/catch block and then throw the correct LdapBindException.

**Comment by douyu** [comment]
you mind me, i use yaf(a web framework), it set a error handler. It a big change for every '@', maybe i can do something in error handler

**Comment by douyu** [comment]
I test the code :
`
    public function handleError($errno, $errstr, $errfile, $errline) {
        if (error_reporting() === 0) {
            return;
        }
        throw new ErrorException($errstr, $errno, 1, $errfile, $errline);
    }
`
it works, you don't need add try catch

**Comment by ChadSikorra** [comment]
Hmm...OK, that does seem to be an issue in the error handler then if it is ignoring the error reporting level. Another thought I had is wrapping the `ldap_*` calls and set a temporary error handler before the function call, then restore the old handler immediately afterwards.

**Comment by ChadSikorra** [comment]
I'm going to close this out since it's not PHP behavior to throw an exception for any of the `ldap_*` functions and the error handler needs to respect the error reporting level (which in this case gets set by `@`). Although it would be nice if the functions threw exceptions by default instead of the current state of things.
